"""empty message

Revision ID: 00de4029c8da
Revises: 4814f393d557
Create Date: 2020-08-15 16:07:29.852663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00de4029c8da'
down_revision = '4814f393d557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('downvotes', sa.Integer(), nullable=False))
    op.add_column('resource', sa.Column('upvotes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'upvotes')
    op.drop_column('resource', 'downvotes')
    # ### end Alembic commands ###
