"""empty message

Revision ID: 4814f393d557
Revises: 3f84c04070b0
Create Date: 2020-08-15 15:56:21.343943

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4814f393d557"
down_revision = "3f84c04070b0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("api_key", sa.Column("level", sa.SmallInteger(), nullable=False))
    op.drop_column("api_key", "is_revoked")
    op.add_column(
        "lemma", sa.Column("type_", postgresql.ARRAY(sa.SmallInteger()), nullable=True)
    )
    op.drop_constraint("resource_parent_id_fkey", "resource", type_="foreignkey")
    op.create_foreign_key(
        None,
        "resource",
        "resource",
        ["parent_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "resource_name_resource_id_fkey", "resource_name", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "resource_name",
        "resource",
        ["resource_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "resource_url_resource_id_fkey", "resource_url", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "resource_url",
        "resource",
        ["resource_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "tags_to_resources_mtm_tag_id_fkey", "tags_to_resources_mtm", type_="foreignkey"
    )
    op.drop_constraint(
        "tags_to_resources_mtm_resource_id_fkey",
        "tags_to_resources_mtm",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "tags_to_resources_mtm",
        "resource",
        ["resource_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "tags_to_resources_mtm",
        "tag",
        ["tag_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tags_to_resources_mtm", type_="foreignkey")
    op.drop_constraint(None, "tags_to_resources_mtm", type_="foreignkey")
    op.create_foreign_key(
        "tags_to_resources_mtm_resource_id_fkey",
        "tags_to_resources_mtm",
        "resource",
        ["resource_id"],
        ["id"],
    )
    op.create_foreign_key(
        "tags_to_resources_mtm_tag_id_fkey",
        "tags_to_resources_mtm",
        "tag",
        ["tag_id"],
        ["id"],
    )
    op.drop_constraint(None, "resource_url", type_="foreignkey")
    op.create_foreign_key(
        "resource_url_resource_id_fkey",
        "resource_url",
        "resource",
        ["resource_id"],
        ["id"],
    )
    op.drop_constraint(None, "resource_name", type_="foreignkey")
    op.create_foreign_key(
        "resource_name_resource_id_fkey",
        "resource_name",
        "resource",
        ["resource_id"],
        ["id"],
    )
    op.drop_constraint(None, "resource", type_="foreignkey")
    op.create_foreign_key(
        "resource_parent_id_fkey", "resource", "resource", ["parent_id"], ["id"]
    )
    op.drop_column("lemma", "type_")
    op.add_column(
        "api_key",
        sa.Column("is_revoked", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("api_key", "level")
    # ### end Alembic commands ###
