"""empty message

Revision ID: 8475f7d96e68
Revises: ab72dc04fec6
Create Date: 2020-08-19 10:45:58.127636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8475f7d96e68"
down_revision = "ab72dc04fec6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "review",
        sa.Column(
            "date_added",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("review", "date_added")
    # ### end Alembic commands ###
