"""empty message

Revision ID: ab72dc04fec6
Revises: b0cf42a78171
Create Date: 2020-08-16 14:08:38.063522

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ab72dc04fec6"
down_revision = "b0cf42a78171"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "lemma", sa.Column("type", postgresql.ARRAY(sa.SmallInteger()), nullable=True)
    )
    op.drop_column("lemma", "type_")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "lemma",
        sa.Column(
            "type_", postgresql.ARRAY(sa.SMALLINT()), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("lemma", "type")
    # ### end Alembic commands ###
