"""empty message

Revision ID: b2d550dc76af
Revises: 0abedf03157b
Create Date: 2020-08-19 15:34:34.400084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b2d550dc76af"
down_revision = "0abedf03157b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "review", sa.Column("modified_date", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("review", "modified_date")
    # ### end Alembic commands ###
